### ISSUE TITLE
Arch repository doesn't work anymore

### ISSUE THREAD

**Issue by chicco-carone** [blacksky3/linux-xanmod#3]
like the title the repository is down and on the site and on pacman it says that it's not available. Its been like this for a few days.  I would like to know if it got moved or the developers are at least trying to get it back up

**Comment by blacksky3** [comment]
Hi the server is down for the moment. We are working on it and it will be up in the next few days

**Comment by chicco-carone** [comment]
I'm still having a lot of issues with the repository and now i need to do an urgent kernel update for a bug that is making my system unstable. Are there still issues with the repository or i can't download it just myself

**Comment by blacksky3** [comment]
Hi The server is back online finaly. And I bump the version of xanmod kernel. Let me know if everything is good on your side and I will close the issue
